version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - '5432:5432'
    networks:
      - hasura
    restart: unless-stopped
    
  graphql-engine:
    image: 'hasura/graphql-engine:v2.0.6'
    ports:
      - '8090:8080'
    depends_on:
      - postgres
    restart: always
    networks:
      - hasura
    environment:
      HASURA_GRAPHQL_DATABASE_URL: 'postgres://postgres:postgrespassword@postgres:5432/postgres'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: 'startup, http-log, webhook-log, websocket-log, query-log'
      HASURA_GRAPHQL_ADMIN_SECRET: '1'
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "RUJaQoJJcmPmnTKpK@39gp3i21CL6lOudQ"}'
      ACTION_BASE_URL: http://localhost:5000

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: smstore-es01
    environment:
      - node.name=smstore-es01
      - cluster.name=smstore-es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/smstore-elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

networks:
  hasura:
    driver: bridge
  postgres:
    driver: bridge
  elastic:
    driver: bridge
volumes:
  db_data: null
  pgadmin_data: null
  data01:
    driver: local

